[package]
name = "csv2json"
version = "0.1.0"
authors = ["Aditya Manthramurthy <aditya.mmy@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.7"
chrono = "0.4.6"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
